### ISSUE TITLE
Lists - Box Format

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#17]
- Need Initial Box format to display fields like genericveryold 
   - with the Image field very prominent.  
- It is OK if the Box style function has a requirement that the first field in the field list, is the image field.

**Comment by yasirkhan177** [comment]
we didn't dealt with images yet. it would be good if i do this after we dealt with images. it will need minor change for me to put it there?

**Comment by cjcornell** [comment]
It the "cards" (or other list format types) are coded as we discussed, then you have created an internal function for "cards" (or boxes, as you decided to call them).  And this internal function
a. formats the box (dimensions, border etc)
b. according to the new field list_style  (a custom class,.. if blank we use a default class)
c. display fields in the box, formatted perhaps similarly to the way you format profile pages, except without using labels.
d. the only exception is when you encounter a format_type=Image
then this image gets formatted at the top of the card (for the basic use case card)
default css formats they image to fix the width of the card ... perhaps with 1px spacing
e. if we want to change this, then we will either use a custom list_style (class) or create a different box function.

**Comment by yasirkhan177** [comment]
i am getting it .. do you want me to put dummy image for now if format_type= image and list format type =cards(boxes) selected?

but i prefer to put this when we dealt with image format type.

**Comment by cjcornell** [comment]
I added a folder - system/images 
and put some stock placeholder images in it - for this milestone and for future.
for now, just make these the rules for displaying an image in the list / box

1. the system will use the first field in the FD records with a format_type CONTAINING the word image    (because there are several image format_types)
2. if the image field for the "list" record is blank then use system/images/NO-IMAGE-AVAILABLE-ICON.jpg
3. if the image field is non-blank, AND if the file exits in /user_uploads  .... then use that image in the list/box - otherwise display the image in #2 

if course, if the list type is a List or Xlist, then don't display the image field in the list display

**Comment by yasirkhan177** [comment]
can you move the task of format_type=images to another milestone? if it's feasible?

**Comment by cjcornell** [comment]
OK - just this one time we will move it to a new milestone

**Comment by yasirkhan177** [comment]
moved images from /system/images to /users_uploads/ .... 

in genericveryold ... in Xlist <<< small image is displayed at left side of the list. let me know if you want to remove but then there will be no difference in Xlist and LIST ..

**Comment by cjcornell** [comment]
No no ... there is one one other big differnce between List and Xlist.  List is one line per record.  Xlist is multiple lines per record.  Thus, no images shown in List (unless maybe it is an icon that fits.

**Comment by yasirkhan177** [comment]
ok no problem but displaying of multiple lines per record is not part of this milestone ,right ? because i read it in another milestone? wanna confirm so i have better idea which issue is solved

**Comment by cjcornell** [comment]
um ...  well no.
Xlist was one of the list types in the original lists milestone and spec.
 it's just been taking so long that I think you forgot it.

**Comment by yasirkhan177** [comment]
so what do you mean by multiple lines ? i mean will it add extra lines or will have some thing extra as well?

**Comment by cjcornell** [comment]
You are over thinking the xlist option a lot.  A regular list should one
display one line per record (like gmail or genericverold )
A multi line list,  xlist will wrap  or display multiple lines of content
per record. ..if there is content to display)

Again,  look at genericverold

**Comment by yasirkhan177** [comment]
means xlist  will not truncate?

**Comment by cjcornell** [comment]
Xlist should not truncate, but it should wrap neatly/
FYI - just to be clear - this task is about the Box format.

**Comment by yasirkhan177** [comment]
i'm done with box format?

**Comment by cjcornell** [comment]
it's just that most of the comments in this task are starting to be about multi-lined lists ... and it is supposed to be about Boxes.

For this task - please let me know the default style for boxes so I can look at it.  The biox style right now is not the same as genericveryold so I need to do some work here, I guess.

**Comment by yasirkhan177** [comment]
application/css/style.css  <<< search for ".project-detail .. the box style is same like genericveryold... but you asked me to remove border.. which i did .. and some padding and margin adjustment. just let me know how you want them to be appear exactly .. styling is never a time taking issue

**Comment by cjcornell** [comment]
this is the problem ...  the same class for all lists.  I suspected that
this was the problem. Each list type should have its own class (though they
could all be based on the same base class) ... while this might surprise
you as something new - it is something I just though was so obvious that it
didn't need to be explained to this level.  But it explains some of the
program behavior I have been seeing.

**Comment by yasirkhan177** [comment]
its not same for all lists.. for thumbview (xlist) different class is being used. and for cards different class is used .. only base class is same

**Comment by cjcornell** [comment]
well my question was about the default classes (styles) for boxes, and the css-style you gave me was the same as for the other lists, or so it seems

**Comment by yasirkhan177** [comment]
it's not ... via jquery .. css classes get changes when you click on list icons...which you can't see in your html source code( even if you view via inspect element ) .. because page doesn't refresh so as DOM

**Comment by cjcornell** [comment]
Well then, how am I (or rather how are you) going to fix the styles (CSS classes) for lisview, xlist, boxes ....   They need fixing and while I was willing to fix them myself, I am not willing to figure this out.  Either it needs to be made much more clear in the style sheet (CSS file) or there's not much I can do to help you close out his task,

**Comment by yasirkhan177** [comment]
i'm not sure how you want GUI .. otherwise i don't have any problem in fixing it .. i added comment in style.css .... 


/***** boxview ****/ <<< cards list

/****listview index.php***/ single lilne list

/****thumbView index.php***/  multi line list

**Comment by cjcornell** [comment]
1. "i'm not sure how you want GUI "
Look at genericveryold  !!!!  Look at the home page for the boxes (and multi-lined lists)

2. 
> /***** boxview ****/ <<< cards list
> /*listview index.php/ single lilne list
> /*thumbView index.php/ multi line list

what does the index.php mean?

**why is this so difficult to understand?? **\
I want the boxes to look llike genericveryold, and styles(classes) where we can adjust each list style if necessary.

**Comment by yasirkhan177** [comment]
index was just added in comment .. i will fix this .. and will make way for you ,so you can adjust them in future (documented)

**Comment by cjcornell** [comment]
Thank you ...  and yes, keep in mind that you will be documenting this soon!

**Comment by yasirkhan177** [comment]
fix the styling issue according to genericveryold .. added comments to style.css ..

**Comment by cjcornell** [comment]
re: styling - OK ....
- But I want to make sure that the 2 types of bix actions are working correctly - and I not sure I understand it yet.
- we need one "action" for clicking the image ...  this is actually the default select option, same for any list
- we need another action, optional, if we desire another button. So we need a name for the button, and a related action   (I assume the css-class will handle the display of the extra button/
- most of this appears to work (except I cannot see how to add the searate action for the button) - and it may only be a matter of documenting it better so I can use it.
- But we have a potential issue ... I am not sure ... if the DD record allows us to toggle between list types (ie checklist and Box ...) will we be able to specify unique parameters for both types of list?

**Comment by yasirkhan177** [comment]
But we have a potential issue ... I am not sure ... if the DD record allows us to toggle between list types (ie checklist and Box ...) will we be able to specify unique parameters for both types of list? <<< didn't get this point .. 

...........

we need one "action" for clicking the image ... this is actually the default select option, same for any list <<< right now default action is different for image .. edit button action and clicking on any list action is same ... 


we need another action, optional, if we desire another button. So we need a name for the button, and a related action (I assume the css-class will handle the display of the extra button/ <<< this feature is not added yet ... explain this

**Comment by cjcornell** [comment]
Explanations:
- in the DD for lists, we can specify several different styles of lists at the same time (toggled):  Boxes, Lists, XLists, CheckLists ...
- Both Boxes and Checklists require *extra* parameters
   - boxes require extra parameters to specify the actions that occur when the user clicks the image, versus the button.
   - boxes require extra parameters to specify what they button "says" and perhaps how it displays
   - checklists require lots of extra parameters to indicate the extra actions, and labels etc
   - these extra options are specified in the DD->list_extra_options field

So ...  I was concerned that
1. the extra parameters required for boxes might conflict with checklists, in the DD->list_extra_options field
2. when the user toggle between checklists and other lists ...that the checklist extra-options still appear, even though the current toggled list is not a checklist

**Comment by yasirkhan177** [comment]
boxes require extra parameters to specify what they button "says" and perhaps how it displays <<< did you ask me to add this feature??? 



2. when the user toggle between checklists and other lists ...that the checklist extra-options still appear, even though the current toggled list is not a checklist <<< this has been fixed...
