### ISSUE TITLE
FD Defaults and Special Cases

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#2]
IN progress - but we can start with these:

DEFAULTS
Blank: help_message, error_message, format_length
Value = 1: privilege_level, visibility, sub__tab_num, dropdown_alias
Value=0: required
true: editable

Special Cases
- field_label_name = Upper(generic_field_name) - replace "_" or ""-" with spaces
- if generic_field_name contains "_id" then field_identifier=KEYFIELD
- field_label_name contains "image" or "photo"  the format_type="image"
- field_label_name contains "image" or "photo"  
   and "profile" or "user" and no "numbers" (1,2,3,4)
   then format_type="profileimage"
- field_label_name contains "image" or "photo"  
   and "project" or "product" and no "numbers" (1,2,3,4)
   then format_type="projectimage"
- 

TBD - later
- detect if the field should be a dropdown. and determin the dropdown_alias.
- if name contains images or gallery - then format type is an image gallery

**Comment by yasirkhan177** [comment]
Defaults ( values ) are confusing

**Comment by cjcornell** [comment]
OK I will write them a different way:

DEFAULTS
help_message, error_message, format_length Default to Blank values
privilege_level, visibility, sub__tab_num, dropdown_alias  all default to "1"
required = 0
editable=true

**Comment by yasirkhan177** [comment]
ok thanks.. its all clear now

**Comment by yasirkhan177** [comment]
field_label_name contains "image" or "photo" the format_type="image"
field_label_name contains "image" or "photo"
and "profile" or "user" and no "numbers" (1,2,3,4) then format_type="profileimage"
field_label_name contains "image" or "photo"
and "project" or "product" and no "numbers" (1,2,3,4) then format_type="projectimage"

......................

what do you mean by """"and "profile" or "user" and no "numbers" (1,2,3,4) then format_type="profileimage"""""" <<< this?

**Comment by cjcornell** [comment]
if field_label_name 
contains ( "image" or "photo") and 
contains ("project" or "product") and 
does not contain [0-9]   (any numbers)
then format_type="projectimage"

**Comment by yasirkhan177** [comment]
field_label_name = imageproject or image_project ? i still didn't get .. give me written example ,,, thanks

**Comment by cjcornell** [comment]
"field_label_name = imageproject or image_project ? "

where did i write that?  what are you referring to.

Again - you are overthinking this! WAYYYYY overthinking this.
 this is just a one-line conditional

examples of field_label names

(below would resolve to format_type="profileimage")
profilephoto
profile_photo
profileimage

(but these would only resolve to format_type="image")
profileimage_1
profile_photo_42
image_14
image
photo

(below would resolve to format_type="projectimage")
projectimage
project_image
project_photo

(but these would only resolve to format_type="image")
project_image23
project_image_1
project_photo_1

everything above is handled by the 3-4 or so special case (conditions) I listed originally
don't overthink or overwork this!

**Comment by yasirkhan177** [comment]
not over thinking. wasn't clear .. its clear now.. thanks

**Comment by cjcornell** [comment]
OK - after my first test ...
seems there were some defaults that I guess I thought were understood:

generic_field_order = the field number order from the target table

display_field_order  = is the incremented field order (usually matches generic_field order) .... but not necesssariy... for instance if we are capturing fields 4-32 ....
then
generic_field_order    display_field_order 
           4                                1
           5                                2
           6                               3
etc

field_label_name = Title/Upper case ... not all-caps.   Just the first letter of every word....

dropdown_alias=blank   (not 1)

**Comment by yasirkhan177** [comment]
ok i have fixed the above stated points. you can check it... Thanks

**Comment by cjcornell** [comment]
when generating FD ...
dropdown_alias still does not default to blank  (is "1", incorrectly)

**Comment by yasirkhan177** [comment]
now dropdown_alias will be set blank by default.

**Comment by cjcornell** [comment]
OK ... closing (cannot test  right now but will trust this is fixed)
